# -*- coding: utf-8 -*-
"""thresholding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X33hyBJ6DiXo8lx38xyzHaGnKhVO1me
"""

# Program developed by
# NAME : HARI PRIYA M
# REG NO : 212224240047

import cv2
import matplotlib.pyplot as plt

# Step 1: Load the image and convert it to grayscale
image = cv2.imread("input.png")  # <-- Replace with your image filename
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Step 2: Apply Global Thresholding (Manually selected threshold)
_, global_thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

# Step 3: Apply Adaptive Thresholding
adaptive_thresh = cv2.adaptiveThreshold(
    gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 11, 2
)

# Step 4: Apply Otsu's Thresholding
_, otsu_thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

# Step 5: Display all results
titles = ["Original Image", "Global Thresholding", "Adaptive Thresholding", "Otsu Thresholding"]
images = [gray, global_thresh, adaptive_thresh, otsu_thresh]

plt.figure(figsize=(10, 7))

for i in range(4):
    plt.subplot(2, 2, i+1)
    plt.imshow(images[i], cmap="gray")
    plt.title(titles[i])
    plt.axis("off")

plt.show()